/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AIaff extends PIaff
{
    private PVar _var_;
    private TEgal _egal_;
    private PExp _exp_;
    private TDotcoma _dotcoma_;

    public AIaff()
    {
        // Constructor
    }

    public AIaff(
        @SuppressWarnings("hiding") PVar _var_,
        @SuppressWarnings("hiding") TEgal _egal_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TDotcoma _dotcoma_)
    {
        // Constructor
        setVar(_var_);

        setEgal(_egal_);

        setExp(_exp_);

        setDotcoma(_dotcoma_);

    }

    @Override
    public Object clone()
    {
        return new AIaff(
            cloneNode(this._var_),
            cloneNode(this._egal_),
            cloneNode(this._exp_),
            cloneNode(this._dotcoma_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIaff(this);
    }

    public PVar getVar()
    {
        return this._var_;
    }

    public void setVar(PVar node)
    {
        if(this._var_ != null)
        {
            this._var_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._var_ = node;
    }

    public TEgal getEgal()
    {
        return this._egal_;
    }

    public void setEgal(TEgal node)
    {
        if(this._egal_ != null)
        {
            this._egal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._egal_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TDotcoma getDotcoma()
    {
        return this._dotcoma_;
    }

    public void setDotcoma(TDotcoma node)
    {
        if(this._dotcoma_ != null)
        {
            this._dotcoma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dotcoma_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._var_)
            + toString(this._egal_)
            + toString(this._exp_)
            + toString(this._dotcoma_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._var_ == child)
        {
            this._var_ = null;
            return;
        }

        if(this._egal_ == child)
        {
            this._egal_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._dotcoma_ == child)
        {
            this._dotcoma_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._var_ == oldChild)
        {
            setVar((PVar) newChild);
            return;
        }

        if(this._egal_ == oldChild)
        {
            setEgal((TEgal) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._dotcoma_ == oldChild)
        {
            setDotcoma((TDotcoma) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
