/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AIsinonI extends PI
{
    private PIsinon _isinon_;

    public AIsinonI()
    {
        // Constructor
    }

    public AIsinonI(
        @SuppressWarnings("hiding") PIsinon _isinon_)
    {
        // Constructor
        setIsinon(_isinon_);

    }

    @Override
    public Object clone()
    {
        return new AIsinonI(
            cloneNode(this._isinon_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIsinonI(this);
    }

    public PIsinon getIsinon()
    {
        return this._isinon_;
    }

    public void setIsinon(PIsinon node)
    {
        if(this._isinon_ != null)
        {
            this._isinon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._isinon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._isinon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._isinon_ == child)
        {
            this._isinon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._isinon_ == oldChild)
        {
            setIsinon((PIsinon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
