/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ANonVideLdvo extends PLdvo
{
    private PLdv _ldv_;
    private TDotcoma _dotcoma_;

    public ANonVideLdvo()
    {
        // Constructor
    }

    public ANonVideLdvo(
        @SuppressWarnings("hiding") PLdv _ldv_,
        @SuppressWarnings("hiding") TDotcoma _dotcoma_)
    {
        // Constructor
        setLdv(_ldv_);

        setDotcoma(_dotcoma_);

    }

    @Override
    public Object clone()
    {
        return new ANonVideLdvo(
            cloneNode(this._ldv_),
            cloneNode(this._dotcoma_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANonVideLdvo(this);
    }

    public PLdv getLdv()
    {
        return this._ldv_;
    }

    public void setLdv(PLdv node)
    {
        if(this._ldv_ != null)
        {
            this._ldv_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ldv_ = node;
    }

    public TDotcoma getDotcoma()
    {
        return this._dotcoma_;
    }

    public void setDotcoma(TDotcoma node)
    {
        if(this._dotcoma_ != null)
        {
            this._dotcoma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dotcoma_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ldv_)
            + toString(this._dotcoma_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ldv_ == child)
        {
            this._ldv_ = null;
            return;
        }

        if(this._dotcoma_ == child)
        {
            this._dotcoma_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ldv_ == oldChild)
        {
            setLdv((PLdv) newChild);
            return;
        }

        if(this._dotcoma_ == oldChild)
        {
            setDotcoma((TDotcoma) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
