/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class TVide extends Token
{
    public TVide()
    {
        super.setText(" ");
    }

    public TVide(int line, int pos)
    {
        super.setText(" ");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TVide(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTVide(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TVide text.");
    }
}
